"""Deterministic public export helpers for CoinFox integration tests."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterable, Mapping

from foxclaw.policy.publication import evaluate_publication

from . import PUBLIC_CONTRACT_VERSION, schema_path
from .schema_validation import validate_json_schema

DISCLOSURE = "Generated by FoxClaw. Informational paper-only. Not individualized advice."
EXPORT_GENERATED_AT = "2026-06-19T18:00:00Z"

CARD_FIXTURE_NAMES = (
    "watch.json",
    "good_signal_bad_trade.json",
    "structured.json",
    "speculative.json",
    "redline.json",
    "reject.json",
)

OUTCOME_FIXTURE_NAMES = ("resolved_postmortem.json",)


def load_fixture_cards(fixture_dir: str | Path) -> list[dict[str, Any]]:
    """Load the canonical public card fixture set."""
    base = Path(fixture_dir)
    return [_load_json(base / name) for name in CARD_FIXTURE_NAMES]


def load_fixture_outcomes(fixture_dir: str | Path) -> list[dict[str, Any]]:
    """Load the canonical public outcome fixture set."""
    base = Path(fixture_dir)
    return [_load_json(base / name) for name in OUTCOME_FIXTURE_NAMES]


def build_scorecard_export(
    cards: Iterable[Mapping[str, Any]],
    *,
    built_at: str = EXPORT_GENERATED_AT,
) -> dict[str, Any]:
    """Build an aggregate public scorecard from public cards."""
    entries = []
    for card in sorted(cards, key=lambda item: str(item["public_intelligence_id"])):
        entries.append(
            {
                "public_intelligence_id": card["public_intelligence_id"],
                "receipt_id": card["receipt_id"],
                "risk_class": card["risk_class"],
                "plan_readiness": card["plan_readiness"],
                "verdict": _verdict_for_card(card),
                "measurements": dict(card["scores"]),
            }
        )
    return {
        "contract_version": PUBLIC_CONTRACT_VERSION,
        "schema_version": "public_scorecard_export.v1",
        "built_at": built_at,
        "author_type": "system",
        "author_display": "FoxClaw",
        "mode": "informational_paper",
        "disclosure": DISCLOSURE,
        "entries": entries,
        "status": {
            "authority": "paper_only",
            "live_execution_allowed": False,
            "not_individualized_advice": True,
        },
    }


def build_export_manifest(
    cards: Iterable[Mapping[str, Any]],
    outcomes: Iterable[Mapping[str, Any]],
    *,
    generated_at: str = EXPORT_GENERATED_AT,
) -> dict[str, Any]:
    """Build the deterministic CoinFox export manifest."""
    cards = list(cards)
    outcomes = list(outcomes)
    return {
        "contract_name": "foxclaw-public-intelligence",
        "contract_version": PUBLIC_CONTRACT_VERSION,
        "generated_at": generated_at,
        "author_type": "system",
        "author_display": "FoxClaw",
        "mode": "informational_paper",
        "disclosure": DISCLOSURE,
        "files": {
            "intelligence_cards": "intelligence_cards.jsonl",
            "scorecard": "scorecard.json",
            "outcomes": "outcomes.jsonl",
        },
        "counts": {
            "intelligence_cards": len(cards),
            "outcomes": len(outcomes),
        },
        "status": {
            "authority": "paper_only",
            "live_execution_allowed": False,
            "not_individualized_advice": True,
        },
    }


def write_coinfox_public_export(
    cards: Iterable[Mapping[str, Any]],
    outcomes: Iterable[Mapping[str, Any]],
    output_dir: str | Path,
    *,
    generated_at: str = EXPORT_GENERATED_AT,
) -> dict[str, Path]:
    """Write the CoinFox reference export files."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    card_list = [dict(card) for card in cards]
    outcome_list = [dict(outcome) for outcome in outcomes]
    for card in card_list:
        validate_public_card(card)
    for outcome in outcome_list:
        validate_public_outcome(outcome)

    manifest = build_export_manifest(card_list, outcome_list, generated_at=generated_at)
    scorecard = build_scorecard_export(card_list, built_at=generated_at)
    paths = {
        "manifest": out / "manifest.json",
        "intelligence_cards": out / "intelligence_cards.jsonl",
        "scorecard": out / "scorecard.json",
        "outcomes": out / "outcomes.jsonl",
    }
    paths["manifest"].write_text(_json(manifest), encoding="utf-8")
    paths["intelligence_cards"].write_text(_jsonl(card_list), encoding="utf-8")
    paths["scorecard"].write_text(_json(scorecard), encoding="utf-8")
    paths["outcomes"].write_text(_jsonl(outcome_list), encoding="utf-8")
    return paths


def validate_public_card(card: Mapping[str, Any]) -> None:
    """Apply schema and semantic public safety checks to a public card."""
    validate_json_schema(card, _load_json(schema_path("public_intelligence_card.schema.json")))
    if "Not individualized advice" not in str(card.get("disclosure", "")):
        raise ValueError("public card disclosure must state not individualized advice")
    result = evaluate_publication(card)
    if not result.allowed:
        raise ValueError("public card failed publication gate: " + ", ".join(result.reason_codes))


def validate_public_outcome(outcome: Mapping[str, Any]) -> None:
    """Apply semantic public safety checks to a public outcome."""
    if outcome.get("contract_version") != PUBLIC_CONTRACT_VERSION:
        raise ValueError("public outcome has unsupported contract_version")
    status = outcome.get("status", {})
    if not isinstance(status, Mapping):
        raise ValueError("public outcome status must be an object")
    if status.get("live_execution_allowed") is not False:
        raise ValueError("public outcome cannot allow live execution")
    if status.get("not_individualized_advice") is not True:
        raise ValueError("public outcome must be marked not individualized advice")


def _verdict_for_card(card: Mapping[str, Any]) -> str:
    risk_class = str(card.get("risk_class", ""))
    plan_readiness = str(card.get("plan_readiness", ""))
    if risk_class == "REJECT":
        return "REJECTED"
    if risk_class == "REDLINE" and plan_readiness != "PAPER_READY":
        return "GOOD_SIGNAL_BAD_TRADE"
    if risk_class == "STRUCTURED" and plan_readiness == "PAPER_READY":
        return "STRUCTURED_READY"
    return f"{risk_class}_INFORMATIONAL"


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _json(value: Mapping[str, Any]) -> str:
    return json.dumps(value, indent=2, sort_keys=True) + "\n"


def _jsonl(values: Iterable[Mapping[str, Any]]) -> str:
    rows = sorted(values, key=lambda item: str(item.get("public_intelligence_id") or item.get("verified_outcome_id")))
    return "".join(json.dumps(row, sort_keys=True) + "\n" for row in rows)
