#!/usr/bin/env python3
"""Build the public-safe FoxClaw demo site for static hosting."""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from html import escape
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from foxclaw.contract.public.export import (  # noqa: E402
    DISCLOSURE,
    load_fixture_cards,
    load_fixture_outcomes,
    write_coinfox_public_export,
)

FIXTURE_DIR = REPO / "tests" / "fixtures" / "public_contract"
DEFAULT_OUTPUT = REPO / "public_site"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="static site output dir")
    parser.add_argument("--fixture-dir", default=str(FIXTURE_DIR), help="public fixture dir")
    args = parser.parse_args(argv)

    result = build_site(Path(args.output), fixture_dir=Path(args.fixture_dir))
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


def build_site(output_dir: Path, *, fixture_dir: Path = FIXTURE_DIR) -> dict[str, Any]:
    """Write a static public demo site and return a build manifest."""
    cards = load_fixture_cards(fixture_dir)
    outcomes = load_fixture_outcomes(fixture_dir)

    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    export_dir = output_dir / "coinfox-export"
    export_paths = write_coinfox_public_export(cards, outcomes, export_dir)

    (output_dir / "index.html").write_text(_render_index(cards, outcomes), encoding="utf-8")
    (output_dir / "styles.css").write_text(_styles(), encoding="utf-8")
    (output_dir / "README.txt").write_text(
        "\n".join(
            [
                "FoxClaw public demo static site.",
                "",
                "This folder is generated by tools/build_public_demo_site.py.",
                "It contains fixture/public-safe/paper-only material only.",
                "Do not add private DBs, Discord archives, Apollo mesh data, or secrets here.",
                "",
            ]
        ),
        encoding="utf-8",
    )

    return {
        "output_dir": str(output_dir),
        "index": str(output_dir / "index.html"),
        "export_files": {name: str(path) for name, path in export_paths.items()},
        "card_count": len(cards),
        "outcome_count": len(outcomes),
        "public_safe": True,
        "paper_only": True,
    }


def _render_index(cards: list[dict[str, Any]], outcomes: list[dict[str, Any]]) -> str:
    rows = "\n".join(_card_row(card) for card in sorted(cards, key=_card_sort_key))
    outcome_rows = "\n".join(_outcome_row(outcome) for outcome in outcomes)
    card_count = len(cards)
    outcome_count = len(outcomes)
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>FoxClaw Public Demo</title>
  <meta name="description" content="Public-safe FoxClaw demo surface for CoinFox testing.">
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <main class="shell">
    <header class="hero">
      <p class="eyebrow">FoxClaw -> CoinFox -> Planifier</p>
      <h1>FoxClaw helps people avoid turning good information into bad decisions.</h1>
      <p class="lede">{escape(DISCLOSURE)}</p>
      <div class="status-grid" aria-label="Demo status">
        <div><span>{card_count}</span><small>public cards</small></div>
        <div><span>{outcome_count}</span><small>outcome receipt</small></div>
        <div><span>0</span><small>live execution paths</small></div>
      </div>
    </header>

    <section class="band">
      <h2>First Encounter</h2>
      <div class="three">
        <article>
          <h3>FoxClaw</h3>
          <p>The judgment layer: evidence, receipts, risk labels, and paper-only decisions.</p>
        </article>
        <article>
          <h3>CoinFox</h3>
          <p>The public social room where structured intelligence can become readable discussion.</p>
        </article>
        <article>
          <h3>Planifier</h3>
          <p>The planning layer where a person turns information into invalidation, sizing, and a journal.</p>
        </article>
      </div>
    </section>

    <section class="band">
      <div class="section-head">
        <h2>Public Intelligence Cards</h2>
        <p>Fixture data only. Public-safe, paper-only, and not individualized advice.</p>
      </div>
      <div class="cards">
        {rows}
      </div>
    </section>

    <section class="band split">
      <div>
        <h2>Public Contract Export</h2>
        <p>CoinFox should consume these files first before any live FoxClaw client exists.</p>
        <ul class="links">
          <li><a href="coinfox-export/manifest.json">manifest.json</a></li>
          <li><a href="coinfox-export/intelligence_cards.jsonl">intelligence_cards.jsonl</a></li>
          <li><a href="coinfox-export/scorecard.json">scorecard.json</a></li>
          <li><a href="coinfox-export/outcomes.jsonl">outcomes.jsonl</a></li>
        </ul>
      </div>
      <div class="callout">
        <h3>Safety Rails</h3>
        <p>Paper-only. No live orders. No funds movement. No private Discord archive. No Apollo private mesh data.</p>
      </div>
    </section>

    <section class="band">
      <h2>Outcome Receipt</h2>
      <div class="outcomes">
        {outcome_rows}
      </div>
    </section>
  </main>
</body>
</html>
"""


def _card_row(card: dict[str, Any]) -> str:
    claim = card["claim"]
    risk = card["risk_classification"]
    tradeability = card["tradeability"]
    scores = card["scores"]
    return f"""<article class="card">
  <div class="card-top">
    <span>{escape(str(card["risk_class"]))}</span>
    <span>{escape(str(card["plan_readiness"]))}</span>
  </div>
  <h3>{escape(str(claim["summary"]))}</h3>
  <p>{escape(str(risk.get("summary", "")))}</p>
  <dl>
    <div><dt>Evidence</dt><dd>{escape(str(scores["evidence_quality"]))}</dd></div>
    <div><dt>Edge</dt><dd>{escape(str(scores["edge"]))}</dd></div>
    <div><dt>Tradeability</dt><dd>{escape(str(scores["tradeability"]))}</dd></div>
  </dl>
  <p class="wait">{escape(str(tradeability["summary"]))}</p>
</article>"""


def _outcome_row(outcome: dict[str, Any]) -> str:
    summary = outcome.get("summary") or outcome.get("outcome_summary") or outcome.get("title")
    if not summary:
        summary = outcome.get("verified_outcome_id", "Public outcome")
    return f"""<article class="outcome">
  <h3>{escape(str(summary))}</h3>
  <p>Authority: {escape(str(outcome.get("status", {}).get("authority", "paper_only")))}</p>
</article>"""


def _card_sort_key(card: dict[str, Any]) -> str:
    return str(card.get("public_intelligence_id") or "")


def _styles() -> str:
    return """
:root {
  color-scheme: light;
  --ink: #182027;
  --muted: #5a6572;
  --line: #d9e1e5;
  --paper: #f7f9f8;
  --panel: #ffffff;
  --green: #1d6b54;
  --gold: #a36922;
  --red: #9d372f;
}

* { box-sizing: border-box; }

body {
  margin: 0;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  background: var(--paper);
  color: var(--ink);
}

a { color: var(--green); font-weight: 700; }

.shell {
  width: min(1120px, calc(100% - 32px));
  margin: 0 auto;
  padding: 32px 0 56px;
}

.hero {
  min-height: 58vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  border-bottom: 1px solid var(--line);
}

.eyebrow {
  color: var(--green);
  font-weight: 800;
  text-transform: uppercase;
  font-size: 0.78rem;
}

h1 {
  max-width: 920px;
  font-size: clamp(2.2rem, 6vw, 5.5rem);
  line-height: 0.98;
  margin: 10px 0 18px;
}

h2 {
  font-size: 1.6rem;
  margin: 0 0 18px;
}

h3 {
  margin: 0 0 10px;
  font-size: 1.05rem;
}

p {
  color: var(--muted);
  line-height: 1.55;
}

.lede {
  max-width: 720px;
  font-size: 1.1rem;
}

.status-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(120px, 1fr));
  gap: 10px;
  max-width: 620px;
  margin-top: 28px;
}

.status-grid div,
.card,
.outcome,
.callout,
.three article {
  background: var(--panel);
  border: 1px solid var(--line);
  border-radius: 8px;
}

.status-grid div {
  padding: 14px;
}

.status-grid span {
  display: block;
  font-size: 1.7rem;
  font-weight: 800;
}

.status-grid small {
  color: var(--muted);
}

.band {
  padding: 34px 0;
  border-bottom: 1px solid var(--line);
}

.three,
.cards {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 14px;
}

.three article,
.card,
.outcome,
.callout {
  padding: 18px;
}

.section-head {
  display: flex;
  justify-content: space-between;
  gap: 18px;
  align-items: end;
}

.section-head p {
  max-width: 420px;
}

.card-top {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
  margin-bottom: 14px;
}

.card-top span {
  display: inline-flex;
  border: 1px solid var(--line);
  border-radius: 999px;
  padding: 4px 8px;
  color: var(--green);
  font-size: 0.76rem;
  font-weight: 800;
}

dl {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 8px;
  margin: 16px 0;
}

dt {
  color: var(--muted);
  font-size: 0.75rem;
}

dd {
  margin: 0;
  font-weight: 800;
}

.wait {
  border-top: 1px solid var(--line);
  padding-top: 12px;
}

.split {
  display: grid;
  grid-template-columns: 1.4fr 0.8fr;
  gap: 18px;
  align-items: start;
}

.links {
  margin: 16px 0 0;
  padding-left: 18px;
}

.links li {
  margin: 7px 0;
}

.outcomes {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 14px;
}

@media (max-width: 820px) {
  .status-grid,
  .three,
  .cards,
  .split,
  .outcomes {
    grid-template-columns: 1fr;
  }

  .section-head {
    display: block;
  }

  .hero {
    min-height: auto;
    padding: 44px 0 32px;
  }
}
"""


if __name__ == "__main__":
    raise SystemExit(main())
