#!/usr/bin/env python3
"""Freeze or check the Forecast Desk SQLite schema artifact."""

from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from datetime import UTC, datetime
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from foxclaw.adapters.event_contracts.storage.schema import (  # noqa: E402
    canonical_schema,
    initialize_schema,
    schema_fingerprint,
)

FROZEN_JSON = REPO / "config" / "forecast_db_schema.frozen.json"
SCHEMA_MD = REPO / "docs" / "forecast_db_schema.md"


def current_artifact() -> dict:
    conn = sqlite3.connect(":memory:")
    try:
        initialize_schema(conn)
        schema = canonical_schema(conn)
        fp = schema_fingerprint(schema)
    finally:
        conn.close()
    return {
        "artifact": "forecast_db_schema",
        "generated": datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "fingerprint": fp,
        "schema": schema,
        "table_count": len(schema["tables"]),
        "index_count": len(schema["indexes"]),
    }


def render_md(artifact: dict) -> str:
    schema = artifact["schema"]
    lines = [
        "# Forecast Desk Database Schema",
        "",
        "> Generated by `tools/freeze_forecast_db_schema.py`; do not hand-edit.",
        f"> Fingerprint `{artifact['fingerprint']}`.",
        "",
        "The Forecast Desk database is node-local and resolved by explicit path, then",
        "`FOXCLAW_FORECAST_DB`, then `./data/forecast_desk.db`. It must not live in a",
        "cloud-sync folder.",
        "",
        f"Schema version: `{schema['schema_version']}`.",
        f"Tables: `{artifact['table_count']}`. Indexes: `{artifact['index_count']}`.",
        "",
    ]
    for table, spec in schema["tables"].items():
        lines.append(f"## `{table}`")
        lines.append("")
        lines.append("| column | type | not null | default | pk |")
        lines.append("|---|---|---|---|---|")
        for col in spec["columns"]:
            default = "" if col["default"] is None else f"`{col['default']}`"
            pk = "" if col["pk"] == 0 else str(col["pk"])
            lines.append(
                f"| `{col['name']}` | {col['type'] or '-'} | "
                f"{'yes' if col['notnull'] else ''} | {default} | {pk} |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    artifact = current_artifact()
    if args.check:
        if not FROZEN_JSON.exists():
            print(f"missing frozen schema artifact: {FROZEN_JSON}", file=sys.stderr)
            return 1
        frozen = json.loads(FROZEN_JSON.read_text(encoding="utf-8"))
        if frozen.get("fingerprint") != artifact["fingerprint"]:
            print(
                f"forecast schema drift: frozen {frozen.get('fingerprint')} "
                f"!= current {artifact['fingerprint']}",
                file=sys.stderr,
            )
            return 1
        print(f"[forecast-schema] OK {artifact['fingerprint'][:12]}")
        return 0

    FROZEN_JSON.parent.mkdir(parents=True, exist_ok=True)
    FROZEN_JSON.write_text(json.dumps(artifact, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    SCHEMA_MD.write_text(render_md(artifact), encoding="utf-8")
    print(f"[forecast-schema] wrote {FROZEN_JSON.relative_to(REPO)}")
    print(f"[forecast-schema] wrote {SCHEMA_MD.relative_to(REPO)}")
    print(f"[forecast-schema] fingerprint {artifact['fingerprint'][:12]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
