#!/usr/bin/env python3
"""Freeze the grove_core.db schema as a versioned, vendor-neutral asset boundary.

The track record (grove_core.db) is the asset (invariant #8). v2 is new code around
proven history, so the *schema* of that history is a contract that must not drift
silently. This tool snapshots the live schema into two committed artifacts:

  - config/db_schema.frozen.json   canonical machine-readable snapshot + fingerprint
  - docs/db_schema.md              human-readable companion (the diligence view)

Vendor-neutral by design (invariant #5): the database is located via, in order,
  1. --db PATH
  2. $FOXCLAW_DB
  3. ./data/grove_core.db   (local, repo-relative — never a cloud-sync path)
No OneDrive/Google/vendor path is ever hardcoded.

Usage:
  python tools/freeze_db_schema.py --db /path/to/grove_core.db   # write artifacts
  python tools/freeze_db_schema.py --db ... --check              # verify, don't write
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
FROZEN_JSON = REPO / "config" / "db_schema.frozen.json"
SCHEMA_MD = REPO / "docs" / "db_schema.md"


def resolve_db(cli_db: str | None) -> Path:
    """Locate the database vendor-neutrally. Never defaults to a cloud-sync path."""
    if cli_db:
        return Path(cli_db)
    env = os.environ.get("FOXCLAW_DB")
    if env:
        return Path(env)
    return REPO / "data" / "grove_core.db"


def canonical_schema(db: Path) -> dict:
    """Extract a deterministic, fingerprint-stable schema snapshot."""
    con = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
    try:
        tables: dict[str, dict] = {}
        for (name,) in con.execute(
            "SELECT name FROM sqlite_master WHERE type='table' "
            "AND name NOT LIKE 'sqlite_%' ORDER BY name"
        ).fetchall():
            cols = []
            for cid, cname, ctype, notnull, dflt, pk in con.execute(
                f'PRAGMA table_info("{name}")'
            ).fetchall():
                cols.append(
                    {
                        "name": cname,
                        "type": (ctype or "").upper(),
                        "notnull": bool(notnull),
                        "default": dflt,
                        "pk": int(pk),
                    }
                )
            tables[name] = {"columns": cols}

        indexes = []
        for iname, tbl, sql in con.execute(
            "SELECT name, tbl_name, sql FROM sqlite_master WHERE type='index' "
            "AND name NOT LIKE 'sqlite_%' ORDER BY name"
        ).fetchall():
            indexes.append({"name": iname, "table": tbl, "sql": _norm(sql)})

        schema = {"tables": tables, "indexes": indexes}
        return schema
    finally:
        con.close()


def _norm(sql: str | None) -> str | None:
    if sql is None:
        return None
    return " ".join(sql.split())


def fingerprint(schema: dict) -> str:
    blob = json.dumps(schema, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(blob).hexdigest()


def render_md(schema: dict, fp: str, generated: str) -> str:
    lines = [
        "# FoxClaw — Frozen Database Schema (`grove_core.db`)",
        "",
        "> **Generated by `tools/freeze_db_schema.py` — do not hand-edit.**",
        f"> Fingerprint `{fp}` · generated {generated}",
        "",
        "This is the **carried-forward asset boundary** (invariant #8). The v2 engine "
        "shadow-validates against this exact schema (Phase 3). Any drift is caught by "
        "`tests/regression/test_db_schema_frozen.py`. The DB is located vendor-neutrally "
        "via `--db` / `$FOXCLAW_DB` / `./data/grove_core.db` — never a cloud-sync path "
        "(invariant #5).",
        "",
        f"**{len(schema['tables'])} tables · {len(schema['indexes'])} indexes**",
        "",
    ]
    for tname, t in schema["tables"].items():
        lines.append(f"## `{tname}`")
        lines.append("")
        lines.append("| column | type | not null | default | pk |")
        lines.append("|---|---|---|---|---|")
        for c in t["columns"]:
            dflt = "" if c["default"] is None else f"`{c['default']}`"
            pk = "" if c["pk"] == 0 else str(c["pk"])
            lines.append(
                f"| `{c['name']}` | {c['type'] or '—'} | "
                f"{'yes' if c['notnull'] else ''} | {dflt} | {pk} |"
            )
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--db", help="path to grove_core.db (else $FOXCLAW_DB, else ./data/grove_core.db)")
    ap.add_argument("--check", action="store_true", help="verify live schema matches frozen; write nothing")
    args = ap.parse_args()

    db = resolve_db(args.db)
    if not db.exists():
        print(f"[freeze] database not found: {db}", file=sys.stderr)
        print("[freeze] pass --db PATH or set FOXCLAW_DB", file=sys.stderr)
        return 2

    schema = canonical_schema(db)
    fp = fingerprint(schema)
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    if args.check:
        if not FROZEN_JSON.exists():
            print(f"[freeze] no frozen artifact at {FROZEN_JSON} — run without --check first", file=sys.stderr)
            return 1
        frozen = json.loads(FROZEN_JSON.read_text(encoding="utf-8"))
        if frozen.get("fingerprint") == fp:
            print(f"[freeze] OK — live schema matches frozen ({fp[:12]}…)")
            return 0
        print(f"[freeze] DRIFT — live {fp[:12]}… != frozen {str(frozen.get('fingerprint'))[:12]}…", file=sys.stderr)
        _print_drift(frozen.get("schema", {}), schema)
        return 1

    artifact = {
        "fingerprint": fp,
        "generated": generated,
        "source_db": db.name,  # name only — never persist a vendor-specific full path
        "table_count": len(schema["tables"]),
        "index_count": len(schema["indexes"]),
        "schema": schema,
    }
    FROZEN_JSON.parent.mkdir(parents=True, exist_ok=True)
    FROZEN_JSON.write_text(json.dumps(artifact, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    SCHEMA_MD.write_text(render_md(schema, fp, generated), encoding="utf-8")
    print(f"[freeze] wrote {FROZEN_JSON.relative_to(REPO)}")
    print(f"[freeze] wrote {SCHEMA_MD.relative_to(REPO)}")
    print(f"[freeze] {len(schema['tables'])} tables · {len(schema['indexes'])} indexes · fingerprint {fp[:12]}…")
    return 0


def _print_drift(old: dict, new: dict) -> None:
    old_t, new_t = set(old.get("tables", {})), set(new.get("tables", {}))
    for t in sorted(new_t - old_t):
        print(f"  + table added: {t}", file=sys.stderr)
    for t in sorted(old_t - new_t):
        print(f"  - table removed: {t}", file=sys.stderr)
    for t in sorted(old_t & new_t):
        oc = {c["name"]: c for c in old["tables"][t]["columns"]}
        nc = {c["name"]: c for c in new["tables"][t]["columns"]}
        for col in sorted(set(nc) - set(oc)):
            print(f"  + {t}.{col} added", file=sys.stderr)
        for col in sorted(set(oc) - set(nc)):
            print(f"  - {t}.{col} removed", file=sys.stderr)
        for col in sorted(set(oc) & set(nc)):
            if oc[col] != nc[col]:
                print(f"  ~ {t}.{col} changed: {oc[col]} -> {nc[col]}", file=sys.stderr)


if __name__ == "__main__":
    raise SystemExit(main())
